# -*- coding: utf-8 -*-
"""final_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e8DkmfvKKjHVrUV-qzBHX1ZmiTftFEPm
"""

import pandas as pd
import numpy as np

from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.statespace.sarimax import SARIMAX
from xgboost import XGBRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_percentage_error

# ===============================
# LOAD DATA
# ===============================
file_path = "Demo_realdata.xlsx"

df = pd.read_excel(file_path)
df.columns = df.columns.str.strip()

df = df.rename(columns={
    "Part_number": "part",
    "Period_month": "month",
    "Consumption": "consumption",
    "Stock_end_of_month": "stock",
    "Internal_leadtime": "internal_lt",
    "External_leadtime": "external_lt"
})

# ===============================
# CLEANING
# ===============================
df["date"] = pd.to_datetime(df["month"], errors="coerce")
df = df.dropna(subset=["date", "consumption", "stock"])
df = df.sort_values(["part", "date"])

df["internal_lt"] = df["internal_lt"].fillna(method="ffill")
df["external_lt"] = df["external_lt"].fillna(method="ffill")

df["consumption"] = pd.to_numeric(df["consumption"], errors="coerce")
df["stock"] = pd.to_numeric(df["stock"], errors="coerce")

# ===============================
# FEATURE ENGINEERING
# ===============================
def create_features(data):
    df = data.copy()
    df["month_num"] = df["date"].dt.month
    df["lag1"] = df["consumption"].shift(1)
    df["lag2"] = df["consumption"].shift(2)
    df["lag3"] = df["consumption"].shift(3)
    df["rolling_mean"] = df["consumption"].rolling(3).mean()
    return df.dropna()

# ===============================
# MODEL EVALUATION
# ===============================
def evaluate_models(ts):

    train = ts[:-6]
    test = ts[-6:]

    series = train.set_index("date")["consumption"]

    try:
        arima = ARIMA(series, order=(1,1,1)).fit()
        m1 = mean_absolute_percentage_error(test["consumption"], arima.forecast(len(test)))
    except:
        m1 = np.inf

    try:
        sarima = SARIMAX(series, order=(1,1,1),
                         seasonal_order=(1,1,1,12)).fit(disp=False)
        m2 = mean_absolute_percentage_error(test["consumption"], sarima.forecast(len(test)))
    except:
        m2 = np.inf

    try:
        feat = create_features(train)
        X = feat[["month_num","lag1","lag2","lag3","rolling_mean"]]
        y = feat["consumption"]

        xgb = XGBRegressor(n_estimators=300, learning_rate=0.05, random_state=42)
        rf = RandomForestRegressor(n_estimators=200, random_state=42)

        xgb.fit(X, y)
        rf.fit(X, y)

        test_feat = create_features(ts).iloc[-len(test):]

        m3 = mean_absolute_percentage_error(test["consumption"],
            xgb.predict(test_feat[["month_num","lag1","lag2","lag3","rolling_mean"]]))

        m4 = mean_absolute_percentage_error(test["consumption"],
            rf.predict(test_feat[["month_num","lag1","lag2","lag3","rolling_mean"]]))
    except:
        m3, m4 = np.inf, np.inf

    model_map = {"ARIMA": m1, "SARIMA": m2, "XGB": m3, "RF": m4}
    return model_map, min(model_map, key=model_map.get)

# ===============================
# FORECAST ALL MODELS
# ===============================
def forecast_all(ts):

    future_dates = pd.date_range(ts["date"].max(), periods=13, freq="M")[1:]

    # ARIMA
    try:
        arima = ARIMA(ts.set_index("date")["consumption"], order=(1,1,1)).fit()
        arima_fc = arima.forecast(12)
    except:
        arima_fc = np.zeros(12)

    # SARIMA
    try:
        sarima = SARIMAX(ts.set_index("date")["consumption"],
                         order=(1,1,1),
                         seasonal_order=(1,1,1,12)).fit(disp=False)
        sarima_fc = sarima.forecast(12)
    except:
        sarima_fc = np.zeros(12)

    # ML models
    feat = create_features(ts)
    X = feat[["month_num","lag1","lag2","lag3","rolling_mean"]]
    y = feat["consumption"]

    xgb = XGBRegressor(n_estimators=300, learning_rate=0.05, random_state=42)
    rf = RandomForestRegressor(n_estimators=200, random_state=42)

    xgb.fit(X, y)
    rf.fit(X, y)

    last_xgb = list(ts["consumption"].values[-3:])
    last_rf = list(ts["consumption"].values[-3:])

    xgb_fc, rf_fc = [], []

    for d in future_dates:
        m = d.month

        # XGB
        l1,l2,l3 = last_xgb[-1], last_xgb[-2], last_xgb[-3]
        rm = np.mean(last_xgb[-3:])
        pred_x = xgb.predict([[m,l1,l2,l3,rm]])[0]
        xgb_fc.append(pred_x)
        last_xgb.append(pred_x)

        # RF
        l1,l2,l3 = last_rf[-1], last_rf[-2], last_rf[-3]
        rm = np.mean(last_rf[-3:])
        pred_r = rf.predict([[m,l1,l2,l3,rm]])[0]
        rf_fc.append(pred_r)
        last_rf.append(pred_r)

    # smoothing
    arima_s = pd.Series(arima_fc).rolling(3,1).mean().values
    sarima_s = pd.Series(sarima_fc).rolling(3,1).mean().values
    xgb_s = pd.Series(xgb_fc).rolling(3,1).mean().values
    rf_s = pd.Series(rf_fc).rolling(3,1).mean().values

    return future_dates, arima_s, sarima_s, xgb_s, rf_s

# ===============================
# MAIN LOOP
# ===============================
results = []

for p in df["part"].unique():

    part_df = df[df["part"] == p].copy()
    if len(part_df) < 12:
        continue

    ts = part_df[["date","consumption"]].copy()

    model_map, best_model = evaluate_models(ts)
    dates, arima, sarima, xgb, rf = forecast_all(ts)

    internal_lt_days = part_df["internal_lt"].mean()
    external_lt_days = part_df["external_lt"].mean()

    for i in range(len(dates)):

        # Select best forecast
        if best_model == "ARIMA":
            demand = arima[i]
        elif best_model == "SARIMA":
            demand = sarima[i]
        elif best_model == "XGB":
            demand = xgb[i]
        else:
            demand = rf[i]

        demand = max(0, demand)

        days = dates[i].days_in_month

        # Internal calculations
        internal_daily_demand = demand / days
        lead_time_demand_internal = internal_daily_demand * internal_lt_days

        # External calculations
        external_daily_demand = demand / days
        lead_time_demand_external = external_daily_demand * external_lt_days

        results.append({
            "Part_number": p,
            "Period_month": dates[i].strftime("%Y-%m"),

            "ARIMA_forecast": arima[i],
            "SARIMA_forecast": sarima[i],
            "XGB_forecast": xgb[i],
            "RF_forecast": rf[i],

            "ARIMA_MAPE": model_map["ARIMA"],
            "SARIMA_MAPE": model_map["SARIMA"],
            "XGB_MAPE": model_map["XGB"],
            "RF_MAPE": model_map["RF"],

            "Best_Model": best_model,
            "Final_Forecast": demand,

            "Internal_LT_days": internal_lt_days,
            "Internal_Daily_Demand": internal_daily_demand,
            "LeadTimeDemand_Internal": lead_time_demand_internal,

            "External_LT_days": external_lt_days,
            "External_Daily_Demand": external_daily_demand,
            "LeadTimeDemand_External": lead_time_demand_external
        })

# ===============================
# OUTPUT
# ===============================
final_df = pd.DataFrame(results)
final_df.to_excel("final_output_no_inventory.xlsx", index=False)

print("Done ✅")